# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rl_l2gar/LowState_rl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rl_l2gar.msg
import unitree_legged_msgs.msg

class LowState_rl(genpy.Message):
  _md5sum = "b77f6762640229fefac4685d9f05c4e0"
  _type = "rl_l2gar/LowState_rl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """unitree_legged_msgs/IMU imu
unitree_legged_msgs/MotorState[20] motorState
userValue_msg userValue
int32 userCmd
================================================================================
MSG: unitree_legged_msgs/IMU
float32[4] quaternion
float32[3] gyroscope
float32[3] accelerometer
int8 temperature
================================================================================
MSG: unitree_legged_msgs/MotorState
uint8 mode           # motor current mode 
float32 q            # motor current position（rad）
float32 dq           # motor current speed（rad/s）
float32 ddq          # motor current speed（rad/s）
float32 tauEst       # current estimated output torque（N*m）
float32 q_raw        # motor current position（rad）
float32 dq_raw       # motor current speed（rad/s）
float32 ddq_raw      # motor current speed（rad/s）
int8 temperature     # motor temperature（slow conduction of temperature leads to lag）
uint32[2] reserve
================================================================================
MSG: rl_l2gar/userValue_msg
float64 lx
float64 ly
float64 rx
float64 ry
float64 L2"""
  __slots__ = ['imu','motorState','userValue','userCmd']
  _slot_types = ['unitree_legged_msgs/IMU','unitree_legged_msgs/MotorState[20]','rl_l2gar/userValue_msg','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       imu,motorState,userValue,userCmd

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LowState_rl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.imu is None:
        self.imu = unitree_legged_msgs.msg.IMU()
      if self.motorState is None:
        self.motorState = [unitree_legged_msgs.msg.MotorState() for _ in range(20)]
      if self.userValue is None:
        self.userValue = rl_l2gar.msg.userValue_msg()
      if self.userCmd is None:
        self.userCmd = 0
    else:
      self.imu = unitree_legged_msgs.msg.IMU()
      self.motorState = [unitree_legged_msgs.msg.MotorState() for _ in range(20)]
      self.userValue = rl_l2gar.msg.userValue_msg()
      self.userCmd = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_4f().pack(*self.imu.quaternion))
      buff.write(_get_struct_3f().pack(*self.imu.gyroscope))
      buff.write(_get_struct_3f().pack(*self.imu.accelerometer))
      _x = self.imu.temperature
      buff.write(_get_struct_b().pack(_x))
      if len(self.motorState) != 20:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (20, len(self.motorState), 'self.motorState')))
      for val1 in self.motorState:
        _x = val1
        buff.write(_get_struct_B7fb().pack(_x.mode, _x.q, _x.dq, _x.ddq, _x.tauEst, _x.q_raw, _x.dq_raw, _x.ddq_raw, _x.temperature))
        buff.write(_get_struct_2I().pack(*val1.reserve))
      _x = self
      buff.write(_get_struct_5di().pack(_x.userValue.lx, _x.userValue.ly, _x.userValue.rx, _x.userValue.ry, _x.userValue.L2, _x.userCmd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.imu is None:
        self.imu = unitree_legged_msgs.msg.IMU()
      if self.motorState is None:
        self.motorState = None
      if self.userValue is None:
        self.userValue = rl_l2gar.msg.userValue_msg()
      end = 0
      start = end
      end += 16
      self.imu.quaternion = _get_struct_4f().unpack(str[start:end])
      start = end
      end += 12
      self.imu.gyroscope = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.imu.accelerometer = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 1
      (self.imu.temperature,) = _get_struct_b().unpack(str[start:end])
      self.motorState = []
      for i in range(0, 20):
        val1 = unitree_legged_msgs.msg.MotorState()
        _x = val1
        start = end
        end += 30
        (_x.mode, _x.q, _x.dq, _x.ddq, _x.tauEst, _x.q_raw, _x.dq_raw, _x.ddq_raw, _x.temperature,) = _get_struct_B7fb().unpack(str[start:end])
        start = end
        end += 8
        val1.reserve = _get_struct_2I().unpack(str[start:end])
        self.motorState.append(val1)
      _x = self
      start = end
      end += 44
      (_x.userValue.lx, _x.userValue.ly, _x.userValue.rx, _x.userValue.ry, _x.userValue.L2, _x.userCmd,) = _get_struct_5di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.imu.quaternion.tostring())
      buff.write(self.imu.gyroscope.tostring())
      buff.write(self.imu.accelerometer.tostring())
      _x = self.imu.temperature
      buff.write(_get_struct_b().pack(_x))
      if len(self.motorState) != 20:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (20, len(self.motorState), 'self.motorState')))
      for val1 in self.motorState:
        _x = val1
        buff.write(_get_struct_B7fb().pack(_x.mode, _x.q, _x.dq, _x.ddq, _x.tauEst, _x.q_raw, _x.dq_raw, _x.ddq_raw, _x.temperature))
        buff.write(val1.reserve.tostring())
      _x = self
      buff.write(_get_struct_5di().pack(_x.userValue.lx, _x.userValue.ly, _x.userValue.rx, _x.userValue.ry, _x.userValue.L2, _x.userCmd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.imu is None:
        self.imu = unitree_legged_msgs.msg.IMU()
      if self.motorState is None:
        self.motorState = None
      if self.userValue is None:
        self.userValue = rl_l2gar.msg.userValue_msg()
      end = 0
      start = end
      end += 16
      self.imu.quaternion = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=4)
      start = end
      end += 12
      self.imu.gyroscope = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.imu.accelerometer = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 1
      (self.imu.temperature,) = _get_struct_b().unpack(str[start:end])
      self.motorState = []
      for i in range(0, 20):
        val1 = unitree_legged_msgs.msg.MotorState()
        _x = val1
        start = end
        end += 30
        (_x.mode, _x.q, _x.dq, _x.ddq, _x.tauEst, _x.q_raw, _x.dq_raw, _x.ddq_raw, _x.temperature,) = _get_struct_B7fb().unpack(str[start:end])
        start = end
        end += 8
        val1.reserve = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=2)
        self.motorState.append(val1)
      _x = self
      start = end
      end += 44
      (_x.userValue.lx, _x.userValue.ly, _x.userValue.rx, _x.userValue.ry, _x.userValue.L2, _x.userCmd,) = _get_struct_5di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
_struct_5di = None
def _get_struct_5di():
    global _struct_5di
    if _struct_5di is None:
        _struct_5di = struct.Struct("<5di")
    return _struct_5di
_struct_B7fb = None
def _get_struct_B7fb():
    global _struct_B7fb
    if _struct_B7fb is None:
        _struct_B7fb = struct.Struct("<B7fb")
    return _struct_B7fb
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
